name: Go
on: 
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      go-version:
        type: string
        default: stable
      path:
        type: string
        default: .
jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - id: setup-go
        name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          check-latest: true
      - id: go-env
        run: |
          echo "::set-output name=GOCACHE::$(go env GOCACHE)"
          echo "::set-output name=GOMODCACHE::$(go env GOMODCACHE)"
      - id: restore-go-mod-cache
        name: Restore the Go module cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-env.outputs.GOMODCACHE }}
          key: go.module-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go.module-cache-
      - name: Verify the Go module
        run: go mod tidy -diff
      - name: Setup the Go build cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-env.outputs.GOCACHE }}
          key: go${{ steps.setup-go.outputs.go-version }}.${{ runner.os }}-${{ runner.arch }}.build-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go${{ steps.setup-go.outputs.go-version }}.${{ runner.os }}-${{ runner.arch }}.build-cache-
      - name: Run tests
        run: go test -race -v ${{ inputs.path }}/...
